"""add inst from portal

Revision ID: 07417d1f777e
Revises: 7da4efa0cb3f
Create Date: 2023-05-18 23:22:38.958222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07417d1f777e'
down_revision = '7da4efa0cb3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('inst_from_portal', sa.Boolean(), nullable=True))
    table_name = sa.sql.table("person", sa.Column("inst_from_portal", sa.Boolean()))
    op.execute("UPDATE person SET inst_from_portal = false")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'inst_from_portal')
    # ### end Alembic commands ###
