"""Add email column to institutions

Revision ID: 23d1c62160fb
Revises: 29b4d4cee1ba
Create Date: 2023-05-30 21:49:20.749806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23d1c62160fb'
down_revision = '29b4d4cee1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('email', sa.String(255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'email')
    # ### end Alembic commands ###
