"""Add is_admin_activate column in user

Revision ID: 29b4d4cee1ba
Revises: 07417d1f777e
Create Date: 2023-05-19 19:24:19.491710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29b4d4cee1ba'
down_revision = '07417d1f777e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin_activate', sa.Integer(), nullable=True))
    op.execute("UPDATE user SET is_admin_activate = 0")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin_activate')
    # ### end Alembic commands ###
