"""Add old_institutions attribute to users

Revision ID: 3ef310cd9649
Revises: df75caff7046
Create Date: 2023-09-13 06:26:46.227196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ef310cd9649'
down_revision = 'df75caff7046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('old_institutions', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'old_institutions')
    # ### end Alembic commands ###
