"""Add studies and studytype models and its relationship

Revision ID: 61b8eba8515b
Revises: 23d1c62160fb
Create Date: 2023-07-28 17:08:05.084462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "61b8eba8515b"
down_revision = "23d1c62160fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "study_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "studies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_person", sa.Integer(), nullable=True),
        sa.Column("id_study_type", sa.Integer(), nullable=False),
        sa.Column("study_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("file_path", sa.String(length=255), nullable=True),
        sa.Column("upload_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_person"],
            ["person.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_study_type"],
            ["study_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("studies")
    op.drop_table("study_type")
    # ### end Alembic commands ###
