"""Add superadmin attribute and institutions relationship

Revision ID: 7da4efa0cb3f
Revises: f62001c27e79
Create Date: 2023-04-21 18:39:19.618083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7da4efa0cb3f'
down_revision = 'f62001c27e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions_user',
        sa.Column('institutions_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['institutions_id'], ['institutions.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('institutions_id', 'user_id')
    )
    op.add_column('user', sa.Column('is_superadmin', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superadmin')
    op.drop_table('institutions_user')
    # ### end Alembic commands ###
