"""Add lat long column to person table

Revision ID: fd3d4196b054
Revises: c974b9d0bd83
Create Date: 2023-05-10 21:32:50.788209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd3d4196b054'
down_revision = 'c974b9d0bd83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('person', sa.Column('long', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'long')
    op.drop_column('person', 'lat')
    # ### end Alembic commands ###
